# ===================================
# 🪄 Pre-commit hooks for Agentify
# Runs code formatting and lint checks before commits
# ===================================

repos:
  # ---------------------------
  # Python (Backend)
  # ---------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5  # use latest
    hooks:
      - id: ruff
        name: Ruff Linter
        types: [python]
        args: ["--fix"]
      - id: ruff-format
        name: Ruff Formatter
        types: [python]

  # ---------------------------
  # JavaScript/TypeScript (Frontend)
  # ---------------------------
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Prettier Formatter
        files: "\\.(js|jsx|ts|tsx|json|css|scss|md|html)$"
        additional_dependencies: ["prettier@3.3.3"]
        args: ["--write"]
        language_version: system

  # ---------------------------
  # General housekeeping
  # ---------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
