[project]
name = "agentify-backend"
version = "0.1.0"
description = "Backend for the agentify application."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.1",
    "firebase-admin>=7.1.0",
    "pydantic>=2.12.0",
    "python-dotenv>=1.1.1",
]
