name: Agentify CI
on:
    push:
      branches: [ main, dev ]
    pull_request:
        branches: [ main, dev ]
jobs:
    # -----------------------------
    # FRONTEND BUILD JOB
    # -----------------------------
    frontend:
      name: Frontend Build
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: agentify-frontend
      steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Setup Node
            uses: actions/setup-node@v4
            with:
              node-version: 20

          - name: Install dependencies
            run: npm ci

          - name: Build project
            run: npm run build
    # -----------------------------
    # BACKEND BUILD JOB
    # -----------------------------
    backend:
      name: Backend Build & Test
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: agentify-backend
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install uv
          run: curl -LsSf https://astral.sh/uv/install.sh | sh

        - name: Verify uv version
          run: uv --version

        - name: Install dependencies
          run: uv sync

        - name: Run tests
          run: uv run pytest || echo "No tests yet"

        - name: Build Docker image
          run: docker build -t agentify-backend:ci .
